apiVersion: v1
kind: Service
metadata:
  name: my-kubernetes-service
spec:
  selector:
    app: my-web-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
  type: LoadBalancer
